### ISSUE TITLE
p_expressions_or is not implemented

### ISSUE THREAD

**Issue by ghost** [h2non/jsonpath-ng#14] opened 2018-01-13 08:52 UTC
Hello,

I would like to ask if there are plans to implement a p_expression_or method in the parser.y

I can see that and (&) is implemented:

```
def p_expressions_and(self, p):

        "expressions : expressions '&' expressions"

        # TODO(sileht): implements '|'

        p[0] = p[1] + p[3]

```
however there is no "or" capability implemented and we cannot filter paths using expressions like:
[?a > 1 or b >1]. Currently only [@a>1 & b>1] is supported.

**Comment by dlacher1** [comment] 2019-05-01 19:47
I started to look into this. when an & operator is detected both items are added to this p[0] list. adding   "expressions : expressions '|' expressions" to a different method gets it to recognize the or. but i dont see where this p[0] list gets processed.

**Comment by michaelmior** [comment] 2024-08-13 14:14
Duplicate of #27

**Closed by michaelmior** 2024-08-13 14:14 UTC
